# Generated by Django 5.0.6 on 2024-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='mascotas/')),
            ],
        ),
    ]
